services:
  forkserver:
    image: oostvoort/forkserver:rust
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '8545:8545'
    environment:
      - SERVER_PORT=3000
      - FORK_PORT=8545
      - FORK_CHAIN_ID=1337
      - FORK_MNEMONIC=test test test test test test test test test test test junk
      - FORK_BLOCK_NUMBER=16669468
      - FORK_JSON_RPC_URL=https://mainnet.infura.io/v3/
      - FORK_BLOCK_TIME=13
  dashboard:
    image: oostvoort/forkserver_dashboard:rust
    restart: unless-stopped
    ports:
      - '8080:8080'
