stages:
  - build
  - deploy
  - post-deploy

docker-build-dev:
  stage: build
  tags:
    - aws-runner
  only:
    refs:
      - develop-admn-ecr
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - amazon-linux-extras install docker
#    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 003476427852.dkr.ecr.ap-southeast-1.amazonaws.com
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 690031684195.dkr.ecr.ap-southeast-1.amazonaws.com
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

  script:
    - echo "Building image..."
    - docker build -t admn_forkserver .
    - echo "Tagging image..."
    - docker tag admn_forkserver:latest 690031684195.dkr.ecr.ap-southeast-1.amazonaws.com/admn_forkserver:latest
    #    - docker tag forkserver-dev:latest 534025418435.dkr.ecr.eu-west-2.amazonaws.com/metaframes-dev-cms:dev-$IMAGE_TAG
    - echo "Pushing image..."
    - docker push 690031684195.dkr.ecr.ap-southeast-1.amazonaws.com/admn_forkserver:latest
#    - docker push 534025418435.dkr.ecr.eu-west-2.amazonaws.com/metaframes-dev-cms:dev-$IMAGE_TAG
#    - aws ecs update-service --service "metaframes-dev-admin" --cluster "metaframes-dev"  --force-new-deployment --region "eu-west-2"
#    - aws ecs wait services-stable --cluster "metaframes-dev" --service "metaframes-dev-admin" --region "eu-west-2"
